name: XiaoniuTech
author: Fangkuai_Xiaoniu
description: 这是你妈的小牛科技
main: me.Xiaoniu.xiaoniutech.XiaoniuTech
website: https://github.com/Slimefun/Addon-Template
version: ${project.version}
api-version: 1.20.1
depend:
- Slimefun
